apiVersion: batch/v1
kind: Job
metadata:
  name: openpitrix-cluster-db-ctrl-job
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    job: openpitrix-cluster-db-ctrl
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: openpitrix
        job: openpitrix-cluster-db-ctrl
      name: openpitrix-cluster-db-ctrl
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.${NAMESPACE}.svc.cluster.local 3306; do echo "waiting for mysql"; sleep 2; done;']
      containers:
      - command: ["flyway", "-X", "-url=jdbc:mysql://openpitrix-db.${NAMESPACE}.svc.cluster.local/cluster", "-user=root", "-validateOnMigrate=false", "-locations=filesystem:/flyway/sql/cluster", "migrate"]
        env:
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        image: ${FLYWAY_IMAGE}
        imagePullPolicy: Always
        name: openpitrix-cluster-db-ctrl
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
