apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  labels:
    app: openpitrix
  name: openpitrix-db-init
  namespace: openpitrix-system
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: openpitrix-db-init
      name: db-init
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.openpitrix-system.svc.cluster.local 3306; do echo "waiting for mysql"; sleep 2; done;']
      containers:
      - command: ["/flyway/sql/ddl/ddl_init.sh", "-hopenpitrix-db.openpitrix-system.svc.cluster.local", "-uroot", "--connect-timeout=5"]
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        image: openpitrix/openpitrix:flyway
        imagePullPolicy: Always
        name: db-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
