apiVersion: batch/v1
kind: Job
metadata:
  name: openpitrix-db-init-job
  labels:
    app: openpitrix
    job: openpitrix-db-init
    version: {{ .Values.version }}
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: openpitrix
        job: openpitrix-db-init
        version: {{ .Values.version }}
      name: openpitrix-db-init
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.{{ .Release.Namespace }}.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      containers:
      - command: ["/flyway/sql/ddl/ddl_init.sh", "-hopenpitrix-db.{{ .Release.Namespace }}.svc", "-uroot", "--connect-timeout=5"]
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        image: {{ .Values.flyway_image }}
        imagePullPolicy: IfNotPresent
        name: openpitrix-db-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
