apiVersion: v1
kind: Service
metadata:
  name: openpitrix-api-gateway
  labels:
    app: openpitrix
    component: openpitrix-api-gateway
    version: {{ .Values.version }}
spec:
  type: NodePort
  selector:
    app: openpitrix
    component: openpitrix-api-gateway
  ports:
  - name: openpitrix-api-gateway
    protocol: TCP
    port: 9100
    targetPort: 9100
    {{ .Values.api_nodeport }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-api-gateway-deployment
  labels:
    app: openpitrix
    component: openpitrix-api-gateway
    version: {{ .Values.version }}
spec:
  selector:
    matchLabels:
      app: openpitrix
      component: openpitrix-api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-api-gateway
        version: {{ .Values.version }}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.{{ .Release.Namespace }}.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.{{ .Release.Namespace }}.svc 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: openpitrix-api-gateway
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.image_pull_policy }}
        command:
          - api-gateway
        ports:
        - containerPort: 9100
          name: api-gateway
        env:
        - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
          value: {{ .Values.grpc_show_error_cause | quote }}
        - name: OPENPITRIX_MYSQL_DATABASE
          value: "openpitrix"
        - name: OPENPITRIX_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        - name: OPENPITRIX_IAM_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key.txt
              name: iam-secret-key
        resources:
          limits:
            cpu: {{ .Values.cpu_limits }}m
            memory: {{ .Values.memory_limits }}Mi
          requests:
            cpu: {{ .Values.cpu_requests }}m
            memory: {{ .Values.memory_requests }}Mi
