apiVersion: v1
kind: Service
metadata:
  name: openpitrix-repo-manager
  labels:
    app: openpitrix
    component: openpitrix-repo-manager
    version: {{ .Values.version }}
spec:
  selector:
    app: openpitrix
    component: openpitrix-repo-manager
  ports:
  - name: openpitrix-repo-manager
    protocol: TCP
    port: 9101
    targetPort: 9101
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-repo-manager-deployment
  labels:
    app: openpitrix
    component: openpitrix-repo-manager
    version: {{ .Values.version }}
spec:
  selector:
    matchLabels:
      app: openpitrix
      component: openpitrix-repo-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-repo-manager
        version: {{ .Values.version }}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.{{ .Release.Namespace }}.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.{{ .Release.Namespace }}.svc 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: openpitrix-repo-manager
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.image_pull_policy }}
        command:
          - repo-manager
        ports:
        - containerPort: 9101
          name: repo-manager
        env:
        - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
          value: {{ .Values.grpc_show_error_cause | quote }}
        - name: OPENPITRIX_LOG_LEVEL
          value: {{ .Values.openpitrix_log_level }}
        - name: OPENPITRIX_MYSQL_DATABASE
          value: "repo"
        - name: OPENPITRIX_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        resources:
          limits:
            cpu: {{ .Values.cpu_limits }}m
            memory: {{ .Values.memory_limits }}Mi
          requests:
            cpu: {{ .Values.cpu_requests }}m
            memory: {{ .Values.memory_requests }}Mi
---
apiVersion: v1
kind: Service
metadata:
  name: openpitrix-repo-indexer
  labels:
    app: openpitrix
    component: openpitrix-repo-indexer
    version: {{ .Values.version }}
spec:
  selector:
    app: openpitrix
    component: openpitrix-repo-indexer
  ports:
  - name: openpitrix-repo-indexer
    protocol: TCP
    port: 9108
    targetPort: 9108
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-repo-indexer-deployment
  labels:
    app: openpitrix
    component: openpitrix-repo-indexer
    version: {{ .Values.version }}
spec:
  selector:
    matchLabels:
      app: openpitrix
      component: openpitrix-repo-indexer
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-repo-indexer
        version: {{ .Values.version }}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.{{ .Release.Namespace }}.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.{{ .Release.Namespace }}.svc 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: openpitrix-repo-indexer
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.image_pull_policy }}
        command:
          - repo-indexer
        ports:
        - containerPort: 9108
          name: repo-indexer
        env:
        - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
          value: {{ .Values.grpc_show_error_cause | quote }}
        - name: OPENPITRIX_LOG_LEVEL
          value: {{ .Values.openpitrix_log_level }}
        - name: OPENPITRIX_MYSQL_DATABASE
          value: "repo"
        - name: OPENPITRIX_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        resources:
          limits:
            cpu: {{ .Values.cpu_limits }}m
            memory: {{ .Values.memory_limits }}Mi
          requests:
            cpu: {{ .Values.cpu_requests }}m
            memory: {{ .Values.memory_requests }}Mi
