apiVersion: v1
kind: Service
metadata:
  name: openpitrix-cluster
  namespace: default
  labels:
    app: openpitrix
    service: cluster
spec:
  selector:
    app: openpitrix
    service: cluster
  ports:
  - name: http
    protocol: TCP
    port: 9103
    targetPort: 9103
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openpitrix-cluster
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        service: cluster
    spec:
      containers:
      - args:
        - cluster
        name: openpitrix-cluster
        image: openpitrix/openpitrix
        ports:
        - containerPort: 9103
        env:
        - name: OPENPITRIX_CONFIG_DB_DBNAME
          value: "openpitrix"
        - name: OPENPITRIX_CONFIG_DB_ROOTPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
