apiVersion: v1
kind: Service
metadata:
  name: openpitrix-pilot-service
  namespace: openpitrix-system
  labels:
    app: openpitrix
    service: pilot
spec:
  selector:
    app: openpitrix
    service: openpitrix-pilot-service
  type: LoadBalancer
  ports:
  - name: openpitrix-pilot-service
    protocol: TCP
    port: 9110
    targetPort: 9110
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-pilot-service
  namespace: openpitrix-system
  labels:
    app: openpitrix
    service: openpitrix-pilot-service
spec:
  selector:
    matchLabels:
      app: openpitrix
      service: openpitrix-pilot-service
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        service: openpitrix-pilot-service
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.openpitrix-system.svc.cluster.local 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.openpitrix-system.svc.cluster.local 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: pilot
        image: openpitrix/openpitrix:metadata
        imagePullPolicy: Always
        command: ['pilot', '-config=/opt/openpitrix/conf/pilot-config.json', 'serve']
        ports:
        - containerPort: 9110
          name: pilot
        env:
        - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
        - name: OPENPITRIX_LOG_LEVEL
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
        - mountPath: /opt/openpitrix/conf
          name: config-volume
      volumes:
      - name: config-volume
        configMap:
          name: openpitrix-pilot-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openpitrix-pilot-config
  namespace: openpitrix-system
data:
  pilot-config.json: |-
    {
        "id": "openpitrix-pilot-001",
        "host": "localhost",
        "listen_port": 9110,
        "log_level": "debug"
    }
