apiVersion: v1
kind: Service
metadata:
  name: openpitrix-app-manager
  namespace: default
  labels:
    app: openpitrix
    service: openpitrix-app-manager
spec:
  selector:
    app: openpitrix
    service: openpitrix-app-manager
  ports:
  - name: openpitrix-app-manager
    protocol: TCP
    port: 9102
    targetPort: 9102
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-app-manager
  namespace: default
  labels:
    app: openpitrix
spec:
  selector:
    matchLabels:
      app: openpitrix
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        service: openpitrix-app-manager
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.default.svc.cluster.local 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.default.svc.cluster.local 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: app-manager
        image: openpitrix/openpitrix:latest
        imagePullPolicy: Always
        command:
          - app-manager
        ports:
        - containerPort: 9102
          name: app-manager
        env:
        - name: OPENPITRIX_LOG_LEVEL
          value: ${OPENPITRIX_LOG_LEVEL}
        - name: OPENPITRIX_MYSQL_DATABASE
          value: "app"
        - name: OPENPITRIX_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
