namespace: openpitrix-system
version: v0.3.1

image: openpitrix/openpitrix:v0.3.1
flyway_image: openpitrix/openpitrix:flyway-v0.3.1
dashboard_image: openpitrix/dashboard:v0.3.1
watcher_image: openpitrix/watcher:latest

image_pull_policy: IfNotPresent
openpitrix_log_level: info


## api_nodeport: "API_NODEPORT=31009"
api_nodeport: ""

## dashboard_nodeport: "DASHBOARD_NODEPORT=31010"
dashboard_nodeport: ""

## pilot_nodeport: "PILOT_NODEPORT=31011"
pilot_nodeport: ""

cpu_requests: 100
memory_requests: 100
cpu_limits: 500
memory_limits: 500

mysql_password: password

iam_secret_key: lrsX5vk03JLNRBI9TnwOPZSNrxFIqvrxajs95MjZSmdsYCEYCPjSI4cLPjG2yT2jQLhKAOHS3lpwr4VyJwZz3ryCluIVb9Smsgq
iam_client_id: JYGJTveVcmuAvV95iNUnKHgQ
iam_client_secret: E3SVNXrZOWvsQ2eyrvs9u4nV
iam_account: HYcida4bFrMP


global_config:
  pilot_ip: 127.0.0.1
  pilot_port: 9114
  default_draft_status: true
  frontgate_auto_delete: true
  frontgate_auto_update: true
  max_repo_events: 20


openpitrix_ca_crt: |-
  -----BEGIN CERTIFICATE-----
  MIIDEDCCAfgCCQDqDxrOSzpKtDANBgkqhkiG9w0BAQsFADBKMQswCQYDVQQGEwJH
  QjEOMAwGA1UEBwwFQ2hpbmExEzARBgNVBAoMCm9wZW5waXRyaXgxFjAUBgNVBAMM
  DW9wZW5waXRyaXguaW8wHhcNMTgwOTEzMTI1NjQxWhcNMjgwOTEwMTI1NjQxWjBK
  MQswCQYDVQQGEwJHQjEOMAwGA1UEBwwFQ2hpbmExEzARBgNVBAoMCm9wZW5waXRy
  aXgxFjAUBgNVBAMMDW9wZW5waXRyaXguaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IB
  DwAwggEKAoIBAQDIe3rCZCEJJAkHe+Zm1C6ufvAZX1Ugq4UHUr51WHNbnDqwn/T3
  HFoLxZEfaoymTyReNw9hzVAzfA3TFW2NXcSIpgsxBw3SngJAlSyvi8vzWmXqHoM/
  VHOtToToFD29ShpqHj4XYl/WX8sdp7Qj+kMr+zTKEnDx9BkCuFPBcdcpWVBCDKjT
  WzdF3ZQjzOx12tzo1w8TYXoN0VWbk7ty6WrClORJEmf/QfzAcgo7tO4LVeSgrGpx
  i7tCqgKNoBQxfXw1AzDA/sf6kvdl72bURuucNinSTIDCfgkKMRsK36sp5H1lb4dX
  Qt8EPLb2Y8C5vKmm9nhSn6LDZ3nPf7B0K5TfAgMBAAEwDQYJKoZIhvcNAQELBQAD
  ggEBADhIS6Otr/7DQ1cqi26J2vp1ar2FWcar91ulrD45zmmKX5Cr5d9cEc0HnygE
  9ofXXc1q6/LZdNIVbjmqG8dm+fQ8WSiRYaisGQzJnH54TQs3fSRoVXRgh4gWDGe7
  ZlCGjmkbJkNVjaQsIRtR1rvJrM5youssse03d85qOWEm/zePNNTMnaJbANw2PsfM
  dZVk6r5RswDei+IrXg8fcJ6pMd5ABR3x6s3J5gL/D1KwSX1944N/CN5FEEr7BR0N
  eGVKcCxhPefvyrmyS91UoGJiluCuOK8BSgZtASromKjJNyDvx62ug1LayPGcQCfA
  ybFTm8V89JW394G13DP8kqbxQIg=
  -----END CERTIFICATE-----

pilot_server_crt: |-
  -----BEGIN CERTIFICATE-----
  MIIDGDCCAgACCQCcplA0OmKxDjANBgkqhkiG9w0BAQsFADBKMQswCQYDVQQGEwJH
  QjEOMAwGA1UEBwwFQ2hpbmExEzARBgNVBAoMCm9wZW5waXRyaXgxFjAUBgNVBAMM
  DW9wZW5waXRyaXguaW8wHhcNMTgwOTEzMTI1NjQ2WhcNMjgwOTEwMTI1NjQ2WjBS
  MQswCQYDVQQGEwJHQjEOMAwGA1UEBwwFQ2hpbmExFTATBgNVBAoMDHBpbG90LXNl
  cnZlcjEcMBoGA1UEAwwTcGlsb3Qub3BlbnBpdHJpeC5pbzCCASIwDQYJKoZIhvcN
  AQEBBQADggEPADCCAQoCggEBAK4hsIFbLg0j7gzQZFAgMFY/yrsOfqqcVZSyD7L7
  G8JY7ksUZ2V419nmPUrvM6MLocg7RpkchSwmiTszEBa/pKfz9RhmC9II3qhPY9TR
  YOa1JTW2bTeZUGpJcSMtQCHmmQPw1dNKVqtFkho7ZMo+yaNL3WaxYg7TxIlURqTz
  sSpS5MMhuYoxwmV3G+RxkIcS4UBW6kz1CDpiYSygpkIkUPI8ahJo5NZHSlhKW5IF
  uEm0zM4nAC04Cuk3NqDNc+iRH38E7F2aNQ2upjvpgrWyTZmfMJWRIdte1+jjMTla
  5u4sYZnbbULn+suQwAbv2TMQzXXnrCw6uz3or31ttC+CC9UCAwEAATANBgkqhkiG
  9w0BAQsFAAOCAQEAR40/NNERa+/lh7G5zj2Vmr6AWJQyaSZW+4SEPGN7Njs8/xnm
  g4sJ7DKeVQjj7eWLrOWL3FKNzRr/yLYIY1JXru6HxfynAt0ronAzx7SRAVR9Wx0c
  libMkB78SUiWNaaw5hYwD19unh3vVdVb0+zWhziN8AWZvugwYcRDvaue4uMKyMbL
  VXTlzscaOTFVDWI7anVvaVbzXeQko+i+X6aNEb1ZQXCi/mYi+vVwM7dqg4qQy38v
  +AyK2JXhQz3GgYmTf/IY9hn59/U1QYY2OOBf0I9uGPi8D3kwOOmJgWGpWqW/snXz
  Fydw4vtgoiGrVQUJ3NCK4T6MsmtkUuUIgtmsbQ==
  -----END CERTIFICATE-----

pilot_server_key: |-
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAriGwgVsuDSPuDNBkUCAwVj/Kuw5+qpxVlLIPsvsbwljuSxRn
  ZXjX2eY9Su8zowuhyDtGmRyFLCaJOzMQFr+kp/P1GGYL0gjeqE9j1NFg5rUlNbZt
  N5lQaklxIy1AIeaZA/DV00pWq0WSGjtkyj7Jo0vdZrFiDtPEiVRGpPOxKlLkwyG5
  ijHCZXcb5HGQhxLhQFbqTPUIOmJhLKCmQiRQ8jxqEmjk1kdKWEpbkgW4SbTMzicA
  LTgK6Tc2oM1z6JEffwTsXZo1Da6mO+mCtbJNmZ8wlZEh217X6OMxOVrm7ixhmdtt
  Quf6y5DABu/ZMxDNdeesLDq7PeivfW20L4IL1QIDAQABAoIBAQCdk2sQhByWU49W
  FTbRs29KfYvN3n4Nkk93sfK2+rnSE3wAgURX9RUP4GRS7UeDIkGS2uE2KTLyEyVY
  ZwsGKwKr4f5HyACmXtRu5vjmW1sfK4myo5UOHTVCGZfCR26jvvN1N3moLLtlXh2q
  k1jQFCWQGlUOWzLrTAOsapFLMCOAseceqgAtjYb+Tp0aX6JHo5Qzb3spuIlF+PQu
  IFv43rrSqMpOifM6CnB5yAqZvYJjc1O85IpETSOCM5ZJzZC46EX4DRd/Xdn0zCcQ
  asID3CBV6TlecSMSY0T/Eze0QXpD9TVT3cazcu9kSotjvxKRn3elHasaLrW+/8BM
  tPkWMjrBAoGBAObflSkOMrTCt5Q4E/0/dKHzooHUbmR6cXQ9f0LQX/WPQkkZVGp0
  vYxp8vwV+TxkC1ySz+zw2bEVL5X/8Tvkk7sQOftbiOfHnBi7GiKsCmX9FdEcXkCo
  k9VH3+iBmAC73BuXK1e/jpTUxrFgi5kZZFWcDkp/evm8VA1NvlY4VWgpAoGBAMEV
  NgNVaD8PvDnbrBdjUpqbxwkyx5mhJUJfQ71PhCCbGmU/REfyKab7qPsbfqPdWW3z
  obQ9vmnJBIsVIfbOm0OBIAPM8RXw2Ftkx2M4f7vQrKJN7VDGm+kFfCdr//55usaN
  12oWUEcsOqB0ZRG2Dh8QkbvXKis89SE2ivzYgOvNAoGAePu7J3uIOM888k/8sZ4a
  GXAZvZ07iC3d3EMJuFKHpp++5Z1/bhXk6nru2QkOxYXLqmRIz2pbOX/XouwvVupu
  O/3B1KVf9c3VT+RkSr0K6e0ZDK6n+YwdhAuZGzcmF2RacJ7kGKSKLBXgVT05ii4T
  NQWFO6bYI5x8E0ilMHtuzhkCgYApF9aTBw5UvYiV18bcg2sFNLo7nu8UJ1PCuHu2
  QsIgHmKTwc9KcKOkwlLIfqWJQobR+9QihDGOWhX5c9nyqS4qQ8UIigmVXdjuOpik
  6VVmJ5dWQ7eKRXrRMTWnPjkRc97oey+piG41d5hSpfMMve5rdh9OFxEGesbA9tbF
  0V4+0QKBgQCjLcdanpIs5YZE2FU/eF9zZK16rNDwQv9XvKhKzhGXjmEIdZFfOaSB
  0pjDR5V0kEmzt+GS8NMlkEzYbAi/H/mPFxLOQ7KcZo39nc7/omAjHFDrH8RUuC0Y
  VPqTAE/eCjK1d7tdjBiS3KjUqooKOXJAyyRdgNzuX582Uz7kLTSw9Q==
  -----END RSA PRIVATE KEY-----

pilot_client_crt: |-
  -----BEGIN CERTIFICATE-----
  MIIDGDCCAgACCQCcplA0OmKxDzANBgkqhkiG9w0BAQsFADBKMQswCQYDVQQGEwJH
  QjEOMAwGA1UEBwwFQ2hpbmExEzARBgNVBAoMCm9wZW5waXRyaXgxFjAUBgNVBAMM
  DW9wZW5waXRyaXguaW8wHhcNMTgwOTEzMTI1NjQ3WhcNMjgwOTEwMTI1NjQ3WjBS
  MQswCQYDVQQGEwJHQjEOMAwGA1UEBwwFQ2hpbmExFTATBgNVBAoMDHBpbG90LWNs
  aWVudDEcMBoGA1UEAwwTcGlsb3Qub3BlbnBpdHJpeC5pbzCCASIwDQYJKoZIhvcN
  AQEBBQADggEPADCCAQoCggEBAMwbpFYH81hj1Dq5dYrZuMkFkxqAYBN9P165+5Ck
  jJ37lu/FVP6WxvfUk90jjNEG/Fr0AbOkk8bdk93rYe3iCFVfP08ck8nzpByDdwC4
  wOlDUaWU0Mbma1iZNwk8lb9oY8BmbwHaZYZ7CQhAVDaEL4+QWa1gskT1bGber5Fa
  hCAeXO8O0LNQehFupygLk+FxTKvkERUF8sIGN08/3HFDdzDzikqIQzsbEcOT0Fkb
  /F8GvwQT8V2CGicVaFf+KJU44H7cQHAMZwWpUX1otrBKKFMC+OAhfkuSLjD6KtGj
  RCH2t9/NJh4AEo3h8TZkbmHoYmi/TOnjbWC91pAI/dC3A50CAwEAATANBgkqhkiG
  9w0BAQsFAAOCAQEAUcY7MmdVYPtI58h32xLGoueAElAt8XXJVPhtai2pwwmz3vgD
  7GpsQDPKXFzaEgbgbK22RtSjJ6YbNyFvQTeIknA1bK19/iXN37HNSYVLKoiUxxux
  /k42lcuhveWW18/mzI6HD03sC2RkNYY3kJA5pRUVVSWokWgFf5OPY+5n0Jt8rr3Q
  6pLlCuoh4CW1dy+0NcS4OfzJFW9DHHB0uSf/za9ts+Pq3erQQlq5FySz340UIxfy
  c2df73P9UE9ER/HmZA9NkaJzqzDbzskeob8Tche321O9F6W3tYmddxBvyOWu6+lz
  9hx5c1hWej+UwICx/EPnAzA+ItR72i0MishhEg==
  -----END CERTIFICATE-----

pilot_client_key: |-
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAzBukVgfzWGPUOrl1itm4yQWTGoBgE30/Xrn7kKSMnfuW78VU
  /pbG99ST3SOM0Qb8WvQBs6STxt2T3eth7eIIVV8/TxyTyfOkHIN3ALjA6UNRpZTQ
  xuZrWJk3CTyVv2hjwGZvAdplhnsJCEBUNoQvj5BZrWCyRPVsZt6vkVqEIB5c7w7Q
  s1B6EW6nKAuT4XFMq+QRFQXywgY3Tz/ccUN3MPOKSohDOxsRw5PQWRv8Xwa/BBPx
  XYIaJxVoV/4olTjgftxAcAxnBalRfWi2sEooUwL44CF+S5IuMPoq0aNEIfa3380m
  HgASjeHxNmRuYehiaL9M6eNtYL3WkAj90LcDnQIDAQABAoIBABny+bWmVR3Ls1Oz
  +GmqvH9yIf2gjJZtufzFEGKXSPlc3xeksuWbLbicYiAfQOviQ3scwoqgRdlmmkIA
  hvbDYePYtCfOrktiml61qA+DbaM6V8sBXHmtGcCt2f1monMvRl9TppFJvtaWFdPi
  udIkhBdwdrZAMOnrediqPw/vvhSHDY5stQikgACB4I3b0qsjnm/qx/kRZLeiEdUY
  qHEa/lP+SqTSigLqCV8P/vGbT5XFzmkHdFmjaxfcn4Q6Gwt631LyVo+mjbVPC3MT
  Xt9szePcHuSZW16FUUFrR7YambSTQ/pTJBmkSKklODXJdKh1KO9G2fEyoFMGAW28
  +hnIYQECgYEA6bz/3muTiO210tTc+iHZ6jrrh6At4BE7G6cReK9mm/EQNMqRq4tp
  9teE/3+FBcX0WcLhyrhuXr33Y/AeEXIVlT4gmRNyRqmLz4an7+GqqTQCMWrNvQ0e
  AUv8v+eQLTnb+C5d6SFyKPJEVbAelP6JWJdUjUpbg0aIlDUOVrbigJECgYEA34wy
  eyYjqpBuMlnuD+MKAGGxoJDyMh8SWEWpfOXESz4GhnDu4ru8CNJz5o3QcZZTR+rc
  8GmZywp+REmXmhl+J09uDsg6WId5yDKEvd9Y6WiuWg406HPk4ZiHpSBTP7wTmodO
  mGZb8cxZW0dMCrwr/gGZqKOxKXfJN2zZOp5c2E0CgYAraHEwUlQs6tCIngWH4n+A
  035oSqQaZ7jNcuJ4wkJRFZzH4RLag+Ki9/V4Kat/nfq6LMoYBtZge/EUu0QqQ0Ck
  3cvaAdWIL/aKDNzlXMh/8euyV75rrKL05LLExPFupL8oQRwpro9v8UYlj7auPvMs
  47XNI5EJOTEmLRBDpGU+MQKBgQCMNpFLMMbaKrETn9hz2oHhb2VMQt3GljqZZ0hB
  cJRIZWUOWjNbv0jXd7j+eSCuvg0KZMOjf3jZI4HDLy2JmEfKPEXZu7js4jx+V0Fv
  HnHUJLaHAbYpvtdmsJcT+Ux+A2eAWzHu4PT2mqfJWtTVPuWQ8kwAvHtYeSuaOgme
  fMnbWQKBgB2ZpQNbk1NQKGVnJX3g8YLGhzQol4oMIpNwYZ0PFqzodVTkzXrYSbT2
  SdNC3tErwy8a/bVA2QlGDgGQruLpWYAEWlJxAs5Y0e+H89HRGd3huQw2EXn5iCYF
  l4iD/U/6pzaaRGYz9PAz35f/IRUvveqck3cWEoslSw2GWJbQIaqB
  -----END RSA PRIVATE KEY-----
