apiVersion: v1
kind: Service
metadata:
  name: openpitrix-hyperpitrix
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-hyperpitrix
    version: ${VERSION}
spec:
  selector:
    app: openpitrix
    component: openpitrix-hyperpitrix
  ports:
  - name: openpitrix-api-manager
    protocol: TCP
    port: 9100
    targetPort: 9100
  - name: openpitrix-app-manager
    protocol: TCP
    port: 9102
    targetPort: 9102
  - name: openpitrix-category-manager
    protocol: TCP
    port: 9113
    targetPort: 9113
  - name: openpitrix-attachment-manager
    protocol: TCP
    port: 9120
    targetPort: 9120
  - name: openpitrix-cluster-manager
    protocol: TCP
    port: 9104
    targetPort: 9104
  - name: openpitrix-im-manager
    protocol: TCP
    port: 9119
    targetPort: 9119
  - name: openpitrix-isv-manager
    protocol: TCP
    port: 9118
    targetPort: 9118
  - name: openpitrix-job-manager
    protocol: TCP
    port: 9106
    targetPort: 9106
  - name: openpitrix-repo-manager
    protocol: TCP
    port: 9101
    targetPort: 9101
  - name: openpitrix-repo-indexer
    protocol: TCP
    port: 9108
    targetPort: 9108
  - name: openpitrix-rp-manager
    protocol: TCP
    port: 9121
    targetPort: 9121
  - name: openpitrix-runtime-manager
    protocol: TCP
    port: 9103
    targetPort: 9103
  - name: openpitrix-task-manager
    protocol: TCP
    port: 9107
    targetPort: 9107
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-hyperpitrix-deployment
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-hyperpitrix
    version: ${VERSION}
spec:
  selector:
    matchLabels:
      app: openpitrix
      component: openpitrix
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix
        version: ${VERSION}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.${NAMESPACE}.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.${NAMESPACE}.svc 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
        - name: hyperpitrix
            image: ${IMAGE}
            imagePullPolicy: ${IMAGE_PULL_POLICY}
            command:
              - hyperpitrix
            ports:
              - containerPort: 9100
                name: api-manager
              - containerPort: 9102
                name: app-manager
              - containerPort: 9108
                name: category-manager
              - containerPort: 9120
                name: attachment-manager
              - containerPort: 9104
                name: cluster-manager
              - containerPort: 9119
                name: im-manager
              - containerPort: 9118
                name: isv-manager
              - containerPort: 9106
                name: job-manager
              - containerPort: 9102
                name: repo-manager
              - containerPort: 9121
                name: repo-indexer
              - containerPort: 9121
                name: rp-manager
              - containerPort: 9103
                name: runtime-manager
              - containerPort: 9107
                name: task-manager
            env:
              - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
                value: "${GRPC_SHOW_ERROR_CAUSE}"
              - name: OPENPITRIX_LOG_LEVEL
                value: ${OPENPITRIX_LOG_LEVEL}
              - name: OPENPITRIX_IAM_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    key: secret-key.txt
                    name: iam-secret-key
              - name: OPENPITRIX_MYSQL_DATABASE_API
                value: "openpitrix"
              - name: OPENPITRIX_MYSQL_DATABASE_APP
                value: "app"
              - name: OPENPITRIX_MYSQL_DATABASE_ATTACHMENT
                value: "attachment"
              - name: OPENPITRIX_MYSQL_DATABASE_CLUSTER
                value: "cluster"
              - name: OPENPITRIX_MYSQL_DATABASE_IM
                value: "im"
              - name: IM_DB_LOG_MODE_ENABLE
                value: "${DB_LOG_MODE_ENABLE}"
              - name: IM_DB_HOST
                value: "openpitrix-db"
              - name: OPENPITRIX_MYSQL_DATABASE_ISV
                value: "isv"
              - name: OPENPITRIX_MYSQL_DATABASE_JOB
                value: "job"
              - name: OPENPITRIX_MYSQL_DATABASE_REPO
                value: "repo"
              - name: OPENPITRIX_MYSQL_DATABASE_RUNTIME
                value: "runtime"
              - name: OPENPITRIX_MYSQL_DATABASE_TASK
                value: "task"
              - name: OPENPITRIX_MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: password.txt
                    name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
