apiVersion: v1
kind: Service
metadata:
  name: openpitrix-market-manager
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-market-manager
    version: ${VERSION}
spec:
  selector:
    app: openpitrix
    component: openpitrix-market-manager
  ports:
  - name:  openpitrix-market-manager
    protocol: TCP
    port: 9116
    targetPort: 9116
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-market-manager-deployment
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-market-manager
    version: ${VERSION}
spec:
  selector:
    matchLabels:
      app: openpitrix
      component: openpitrix-market-manager
  replicas: ${MARKET_REPLICA}
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-market-manager
        version: ${VERSION}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.${NAMESPACE}.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.${NAMESPACE}.svc 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: openpitrix-market-manager
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - market-manager
        ports:
        - containerPort: 9116
          name: market-manager
        env:
        - name: OPENPITRIX_LOG_LEVEL
          value: ${OPENPITRIX_LOG_LEVEL}
        - name: OPENPITRIX_MYSQL_DATABASE
          value: "market"
        - name: OPENPITRIX_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        resources:
          limits:
            cpu: ${LIMITS}m
            memory: ${LIMITS}Mi
          requests:
            cpu: ${REQUESTS}m
            memory: ${REQUESTS}Mi
