apiVersion: v1
kind: Service
metadata:
  name: openpitrix-account-service
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-account-service
    version: ${VERSION}
spec:
  selector:
    app: openpitrix
    component: openpitrix-account-service
  ports:
  - name: openpitrix-account-service
    protocol: TCP
    port: 9115
    targetPort: 9115
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-account-service-deployment
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-account-service
    version: ${VERSION}
spec:
  selector:
    matchLabels:
      app: openpitrix
      component: openpitrix-account-service
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-account-service
        version: ${VERSION}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.${NAMESPACE}.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.${NAMESPACE}.svc 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: openpitrix-account-service
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - account-service
        ports:
        - containerPort: 9115
          name: account-service
        env:
        - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
          value: "${GRPC_SHOW_ERROR_CAUSE}"
        - name: OPENPITRIX_LOG_LEVEL
          value: ${OPENPITRIX_LOG_LEVEL}
        - name: OPENPITRIX_MYSQL_DATABASE
          value: "iam"
        - name: OPENPITRIX_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        - name: OPENPITRIX_IAM_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key.txt
              name: iam-secret-key
        - name: IAM_INIT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id.txt
              name: iam-client
        - name: IAM_INIT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret.txt
              name: iam-client
        - name: IAM_INIT_ACCOUNT_EMAIL
          value: "admin@op.com"
        - name: IAM_INIT_ACCOUNT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password.txt
              name: iam-account
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
