consumes:
  - application/json
  - application/yaml
produces:
  - application/json
  - application/yaml
schemes:
  - http
  - https
swagger: '2.0'
info:
  description: >-
    An open platform to package and deploy applications into multiple
    environment such as QingCloud, AWS, Kubernetes etc.
  title: AppHub
  version: 0.1.0
paths:
  /clusters:
    get:
      summary: Gets some clusters
      description: Returns a list containing all clusters.
      parameters:
        - $ref: '#/parameters/pageSize'
        - $ref: '#/parameters/pageNumber'
      tags:
        - cluster
      responses:
        '200':
          description: A list of Cluster
          schema:
            allOf:
              - $ref: '#/definitions/Clusters'
              - $ref: '#/definitions/Paging'
        '500':
          $ref: '#/responses/Standard500ErrorResponse'
    post:
      summary: Creates a cluster
      description: Adds a new cluster to the clusters list.
      parameters:
        - name: cluster
          in: body
          description: The cluster to create.
          schema:
            $ref: '#/definitions/Cluster'
      tags:
        - cluster
      responses:
        '204':
          description: Cluster succesfully created.
        '400':
          description: Cluster couldn't have been created.
        '500':
          $ref: '#/responses/Standard500ErrorResponse'
  '/clusters/{id}':
    get:
      summary: Gets a cluster
      description: Returns a single cluster by its id
      parameters:
        - $ref: '#/parameters/id'
      tags:
        - cluster
      responses:
        '200':
          description: A Cluster
          schema:
            $ref: '#/definitions/Cluster'
        '404':
          $ref: '#/responses/ClusterDoesNotExistResponse'
        '500':
          $ref: '#/responses/Standard500ErrorResponse'
    delete:
      summary: Deletes a cluster
      description: Delete a single cluster identified via its id
      tags:
        - cluster
      responses:
        '204':
          description: Cluster successfully deleted.
        '404':
          $ref: '#/responses/ClusterDoesNotExistResponse'
        '500':
          $ref: '#/responses/Standard500ErrorResponse'
definitions:
  Cluster:
    required:
      - id
    properties:
      name:
        type: string
      description:
        type: string
      id:
        type: string
        pattern: 'cl-[a-zA-Z0-9]{11}'
        minLength: 11
        maxLength: 11
      createTime:
        type: string
        format: date-time
        readOnly: true
  Clusters:
    properties:
      items:
        type: array
        uniqueItems: true
        items:
          $ref: '#/definitions/Cluster'
  Paging:
    properties:
      totalItems:
        type: integer
      totalPages:
        type: integer
      pageSize:
        type: integer
      currentPage:
        type: integer
  Error:
    properties:
      code:
        type: string
        enum:
          - DBERR
          - NTERR
          - UNERR
      message:
        type: string
responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: '#/definitions/Error'
  ClusterDoesNotExistResponse:
    description: The cluster does not exist.
parameters:
  pageSize:
    name: pageSize
    in: query
    description: Number of clusters returned
    type: integer
    format: int32
    minimum: 0
    exclusiveMinimum: true
    exclusiveMaximum: false
    multipleOf: 10
    default: 20
  pageNumber:
    name: pageNumber
    in: query
    description: Page number
    type: integer
    default: 1
  id:
    name: id
    in: path
    required: true
    description: The cluster's id
    type: string
